'use strict'

const fs = require('fs-extra')
const p = require('path')
const normalize = require('normalize-path')

/**
 * Copies the source to a new temporary directory
 * @param  {object} logger  A logging helper to log progress and errors
 * @param  {object} program The object generated by Commander
 * @return {Promise}        An empty Promise
 */
module.exports = (logger, program) => {

  return new Promise((resolve, reject) => {
    fs.copy(program.source, program.tempSource, err => {
      if (err) {
        logger.error('Copy source directory failed:', err)
        return reject('Build failed!')
      }

      logger.info('Copied source directory to temporary directory')
      resolve()
    })
  })

}
