'use strict'

const fs = require('fs-extra')

/**
 * Removes an existing built zip file
 * @param  {object} logger  A logging helper to log progress and errors
 * @param  {object} program The object generated by Commander
 * @return {Promise}        An empty Promise
 */
module.exports = (logger, program) => {

  return new Promise((resolve, reject) => {
    fs.remove(program.zipPath, () => {
      logger.info('Removed old zip file')

      resolve()
    })

  })

}
