'use strict'

const fs = require('fs-extra')

/**
 * Removes the temporary source  directory
 * @param  {object} logger  A logging helper to log progress and errors
 * @param  {object} program The object generated by Commander
 * @return {Promise}        An empty Promise
 */
module.exports = (logger, program) => {

  return new Promise((resolve, reject) => {
    fs.remove(program.tempSource, err => {
      if (err) {
        winston.error(`Error deleting ${program.tempSource}:`, err)
        return reject('Build failed!');
      }

      logger.info('Removed temporary directory')
      resolve();
    })
  })

}
