'use strict'

const fs = require('fs-extra')
const archive = require('archiver')('zip')

/**
 * Compresses the temporary zip file
 * @param  {object} logger  A logging helper to log progress and errors
 * @param  {object} program The object generated by Commander
 * @return {Promise}        An empty Promise
 */
module.exports = (logger, program) => {

  return new Promise((resolve, reject) => {
    const output = fs.createWriteStream(program.zipPath)

    // Events
    output.on('close', () => {
      logger.info(`Zip file created at ${program.zipPath}`)
      resolve()
    })

    output.on('error', err => {
      logger.error('Failed creating zip file:', err)
      reject('Build failed!')
    })

    archive.on('entry', file => {
      logger.info(`Added entry ${file.name}`)
    })

    // Compress
    archive.pipe(output)
    archive.directory(program.tempSource, false).finalize()
  })

}
